# Generated by Django 2.1.7 on 2019-04-19 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingprofile',
            name='customer_id',
        ),
    ]
