# Generated by Django 2.1.7 on 2019-04-03 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190403_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='carts',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
