# Generated by Django 2.1.7 on 2019-05-05 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_is_digital'),
        ('billing', '0009_charge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0008_auto_20190505_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refunded', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('billing_profile', models.ForeignKey(on_delete='billing_profile', to='billing.BillingProfile')),
                ('product', models.ForeignKey(on_delete='product', to='products.Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
