# Generated by Django 2.1.7 on 2019-05-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190505_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchase',
            name='order_id',
            field=models.CharField(max_length=120),
        ),
    ]
