# Generated by Django 2.1.7 on 2019-03-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='abs'),
            preserve_default=False,
        ),
    ]
