# Generated by Django 2.1.7 on 2019-03-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20190327_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-price',)},
        ),
    ]
