# Generated by Django 2.1.7 on 2019-03-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20190327_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slugcom',
            field=models.BooleanField(default=False),
        ),
    ]
