# Generated by Django 2.1.7 on 2019-04-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_slugcom'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vagitable', 'Vagitable'), ('book', 'book'), ('electronic', 'Electronic')], default='vagitable', max_length=120),
        ),
    ]
