# Generated by Django 2.1.7 on 2019-05-06 05:02

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_productfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Md_Nadir\\Desktop\\Py\\static_cdn\\prem_pro_root'), upload_to=products.models.upload_product_file_path),
        ),
    ]
