# Generated by Django 2.1.7 on 2019-05-06 05:04

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20190506_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(upload_to=products.models.upload_product_file_path),
        ),
    ]
