# Generated by Django 2.1.7 on 2019-05-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20190506_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfile',
            name='free',
        ),
    ]
