# Generated by Django 2.1.7 on 2019-05-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_productfile_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfile',
            name='nameT',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
