# Generated by Django 2.1.7 on 2019-07-12 10:22

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20190507_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Md_Nadir\\Envs\\ecommerce\\static_cdn\\prem_pro_root'), upload_to=products.models.upload_product_file_path),
        ),
    ]
