# Generated by Django 2.1.7 on 2019-07-13 09:04

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20190712_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Md_Nadir\\Envs\\ecommerce\\Boitarani\\static_cdn\\prem_pro_root'), upload_to=products.models.upload_product_file_path),
        ),
        migrations.AlterField(
            model_name='productfile',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
